# Generated by Django 4.0.5 on 2022-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlink', '0002_cliente_compra_pagamento_personaltrainer_planotreino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotreino',
            name='imagem',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
