# Generated by Django 4.0.5 on 2022-06-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlink', '0003_planotreino_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
