# Generated by Django 4.0.5 on 2022-06-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitlink', '0004_exercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitlink.cliente')),
                ('refPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitlink.personaltrainer')),
            ],
        ),
    ]
