# Generated by Django 4.0.5 on 2022-06-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitlink', '0005_subscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='refCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitlink.cliente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExercicioPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrBloco', models.IntegerField()),
                ('periodoBloco', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('pesoUsado', models.FloatField()),
                ('feito', models.IntegerField()),
                ('refExercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitlink.exercicio')),
                ('refPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitlink.planotreino')),
            ],
        ),
    ]
