# Generated by Django 4.0.5 on 2022-06-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitlink', '0006_compra_refcliente_exercicioplano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicioplano',
            name='feito',
        ),
        migrations.RemoveField(
            model_name='exercicioplano',
            name='pesoUsado',
        ),
    ]
