# Generated by Django 4.0.5 on 2022-06-21 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitlink', '0007_remove_exercicioplano_feito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='refCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
