# Generated by Django 4.0.5 on 2022-06-21 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitlink', '0008_alter_compra_refcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltrainer',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='planotreino',
            name='refPersonalTrainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='refCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='refPT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='PersonalTrainer',
        ),
    ]
